ARG BUILDTAG=build
FROM diproxy:${BUILDTAG}
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/
LABEL org.opencontainers.image.authors="Hystax"

COPY diproxy/pyproject.toml diproxy/uv.lock diproxy/.pylintrc diproxy/.coveragerc diproxy/
RUN uv --project diproxy sync --locked
COPY diproxy/diproxy/tests diproxy/diproxy/tests
