ARG BUILDTAG=build
FROM bumiworker:${BUILDTAG}
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

COPY bumiworker/pyproject.toml bumiworker/uv.lock bumiworker/.pylintrc ./bumiworker/
RUN uv --project bumiworker sync --locked
