upstream ngui_upstream {
    server ngui:4000;
}

upstream auth_upstream {
    server auth:8905;
}

upstream restapi_upstream {
    server restapi:8999;
}

upstream jira_bus_upstream {
    server jira-bus:8977;
}

server {
    listen 80;
    server_name _;

    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection $connection_upgrade;

    location = /api {
        proxy_pass http://ngui_upstream;
    }

    location /api/ {
        proxy_pass http://ngui_upstream;
    }

    location /auth/ {
        proxy_pass http://auth_upstream;
    }

    location /restapi/ {
        proxy_pass http://restapi_upstream;
    }

    location /jira_bus/ {
        proxy_pass http://jira_bus_upstream;
    }

    location / {
        proxy_pass http://ngui_upstream;
    }
}

map $http_upgrade $connection_upgrade {
    default upgrade;
    '' close;
}
