ARG BUILDTAG=build
FROM jira_bus:${BUILDTAG}
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

WORKDIR /usr/src/app/

COPY jira_bus/pyproject.toml jira_bus/uv.lock ./jira_bus/
COPY jira_bus/.pylintrc jira_bus/.coveragerc ./jira_bus/

COPY tools/check_alembic_down_revisions tools/check_alembic_down_revisions
COPY optscale_client/jira_bus_client optscale_client/jira_bus_client

RUN uv --project jira_bus sync --locked

COPY jira_bus/jira_bus_server/tests jira_bus/jira_bus_server/tests
