"""add_gemini_data_table

Revision ID: 3f8a9c2b7d1e
Revises: 2e3b5da63ef4
Create Date: 2026-03-25 12:44:18.231206

"""
import logging
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "3f8a9c2b7d1e"
down_revision = "2e3b5da63ef4"
branch_labels = None
depends_on = None

LOG = logging.getLogger(__name__)


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'gemini_data',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('created_at', sa.Integer(), nullable=False),
        sa.Column('gemini_id', sa.String(length=36), nullable=False),
        sa.Column('buckets', sa.String(length=256), nullable=False),
        sa.Column(
            "status",
            sa.Enum("CREATED", "QUEUED", "RUNNING", "FAILED", "SUCCESS"),
            nullable=False),
        sa.Column('url', sa.String(length=256), nullable=True),
        sa.Column('valid_until', sa.Integer(), nullable=False),
        sa.Column('deleted_at', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ['gemini_id'], ['organization_gemini.id'], ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_gemini_id'), 'gemini_data',
                    ['gemini_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gemini_id'), table_name='gemini_data')
    op.drop_table('gemini_data')
    # ### end Alembic commands ###
