""""rule_operator"

Revision ID: c9f036cdbcce
Revises: 0b084e91c1ff
Create Date: 2025-06-03 06:20:31.687417

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c9f036cdbcce'
down_revision = '0b084e91c1ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rule',
                  sa.Column('operator', sa.Enum('AND', 'OR'),
                            nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rule', 'operator')
    # ### end Alembic commands ###
