ARG BUILDTAG=build
FROM auth:${BUILDTAG}
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

LABEL org.opencontainers.image.authors="Hystax"

COPY tools/check_alembic_down_revisions tools/check_alembic_down_revisions
COPY optscale_client/auth_client /usr/src/app/optscale_client/auth_client
COPY auth/.pylintrc auth/.coveragerc auth/pyproject.toml auth/uv.lock auth/__init__.py ./auth/

RUN uv --project auth sync --locked

COPY auth/auth_server/tests auth/auth_server/tests
