ARG BUILDTAG=build
FROM clickhouse/clickhouse-server:24.12 AS clickhouse
FROM rest_api:${BUILDTAG}

COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

LABEL org.opencontainers.image.authors="Hystax"

COPY rest_api/pyproject.toml rest_api/uv.lock rest_api/.pylintrc rest_api/.coveragerc rest_api/__init__.py ./rest_api/
COPY tools/check_alembic_down_revisions tools/check_alembic_down_revisions
COPY tools/cloud_adapter tools/cloud_adapter
COPY optscale_client/rest_api_client optscale_client/rest_api_client

RUN uv --project rest_api sync --locked

COPY rest_api/rest_api_server/tests rest_api/rest_api_server/tests
COPY rest_api/prepare_clickhouse_local.sh rest_api/prepare_clickhouse_local.sh
COPY --from=clickhouse /usr/bin/clickhouse rest_api/.clickhouse/clickhouse
