"""initial

Revision ID: e4e5a2956181
Revises:
Create Date: 2025-07-30 08:25:06.801898

"""
from alembic import op
import sqlalchemy as sa
import uuid
from datetime import datetime, UTC


# revision identifiers, used by Alembic.
revision = 'e4e5a2956181'
down_revision = None
branch_labels = None
depends_on = None

subscription_status_enum = sa.Enum(
    'active', 'limit_exceeded', 'suspended', name='subscription_status_enum'
)
stripe_status_enum = sa.Enum(
    'incomplete', 'incomplete_expired', 'trialing', 'active', 'past_due',
    'canceled', 'unpaid', 'paused', name='stripe_status_enum'
)
default_plan_template = {
    'name': 'Free',
    'limits': {
        'month_expenses': 5000
    },
    'customer_id': None,
    'price_id': None,
    'trial_days': 0,
    'grace_period_days': 7,
    'default': True,
    'deleted_at': 0,
}


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'customer',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('owner_id', sa.String(length=36), nullable=False),
        sa.Column('stripe_customer_id', sa.String(length=64), nullable=True),
        sa.Column('name', sa.String(length=255), nullable=True),
        sa.Column('created_at', sa.Integer(), nullable=False),
        sa.Column('deleted_at', sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(
        op.f('ix_customer_owner_id'),
        'customer', ['owner_id'], unique=False)
    op.create_index(
        op.f('ix_customer_stripe_customer_id'),
        'customer', ['stripe_customer_id'], unique=False)
    op.create_table(
        'plan',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('limits', sa.JSON(), nullable=True),
        sa.Column('qty_unit', sa.String(length=36), nullable=True),
        sa.Column('customer_id', sa.String(length=36), nullable=True),
        sa.Column('price_id', sa.String(length=36), nullable=True),
        sa.Column('price', sa.Float(), nullable=True),
        sa.Column('currency', sa.String(length=36), nullable=True),
        sa.Column('trial_days', sa.Integer(), nullable=False),
        sa.Column('grace_period_days', sa.Integer(), nullable=False),
        sa.Column('default', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.Integer(), nullable=False),
        sa.Column('deleted_at', sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'subscription',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('plan_id', sa.String(length=36), nullable=False),
        sa.Column('customer_id', sa.String(length=36), nullable=False),
        sa.Column('quantity', sa.Integer(), nullable=False),
        sa.Column('status', subscription_status_enum,
                  nullable=False, server_default='active'),
        sa.Column('stripe_subscription_id', sa.String(length=36), nullable=True),
        sa.Column('stripe_status', stripe_status_enum, nullable=True),
        sa.Column('cancel_at_period_end', sa.Boolean(), nullable=False),
        sa.Column('end_date', sa.Integer(), nullable=False),
        sa.Column('grace_period_start', sa.Integer(), nullable=False),
        sa.Column('trial_used', sa.Boolean(), nullable=False),
        sa.Column('updated_at', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.Integer(), nullable=False),
        sa.Column('deleted_at', sa.Integer(), nullable=False),

        sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
        sa.ForeignKeyConstraint(['plan_id'], ['plan.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(
        op.f('ix_subscription_customer_id'),
        'subscription', ['customer_id'], unique=False)

    # create default plan
    plan_table = sa.table(
        'plan',
        sa.column('name', sa.String),
        sa.column('limits', sa.JSON),
        sa.column('customer_id', sa.String),
        sa.column('price_id', sa.String),
        sa.column('trial_days', sa.Integer),
        sa.column('grace_period_days', sa.Integer),
        sa.column('default', sa.Boolean),
        sa.column('id', sa.String),
        sa.column('created_at', sa.Integer),
        sa.column('deleted_at', sa.Integer),
    )

    op.bulk_insert(plan_table, [
        {
            'id': str(uuid.uuid4()),
            'created_at': int(datetime.now(tz=UTC).timestamp()),
            **default_plan_template
        }
    ])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subscription_customer_id'), table_name='subscription')
    op.drop_table('subscription')
    op.drop_table('plan')
    op.drop_index(op.f('ix_customer_stripe_customer_id'), table_name='customer')
    op.drop_index(op.f('ix_customer_owner_id'), table_name='customer')
    op.drop_table('customer')
    # ### end Alembic commands ###
