ARG BUILDTAG=build
FROM trapper_worker:${BUILDTAG}
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/
LABEL org.opencontainers.image.authors="Hystax"

COPY trapper/.pylintrc trapper/.coveragerc ./trapper/
COPY trapper/trapper_worker/pyproject.toml trapper/trapper_worker/uv.lock ./trapper/trapper_worker/

RUN uv --project trapper/trapper_worker sync --locked
