ARG BUILDTAG=build
FROM diworker:${BUILDTAG}
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

COPY diworker/pyproject.toml diworker/uv.lock diworker/.pylintrc ./diworker/
RUN uv --project diworker sync --locked
