ARG BUILDTAG=build
FROM katara_service:${BUILDTAG}
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/
LABEL org.opencontainers.image.authors="Hystax"

WORKDIR /usr/src/app/

COPY katara/katara_service/pyproject.toml katara/katara_service/uv.lock ./katara/karara_service/
COPY katara/.pylintrc katara/.coveragerc ./katara/katara_service/

COPY tools/check_alembic_down_revisions tools/check_alembic_down_revisions
COPY optscale_client/katara_client optscale_client/katara_client

RUN uv --project katara/katara_service sync --locked
COPY katara/katara_service/tests katara/katara_service/tests
