ARG BUILDTAG=build
FROM trapper_scheduler:${BUILDTAG}
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/
LABEL org.opencontainers.image.authors="Hystax"

COPY trapper/.pylintrc trapper/.coveragerc ./trapper/
COPY trapper/trapper_scheduler/pyproject.toml trapper/trapper_scheduler/uv.lock ./trapper/trapper_scheduler/

RUN uv --project trapper/trapper_scheduler sync --locked
