ARG BUILDTAG=build
FROM gemini_scheduler:${BUILDTAG}
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

WORKDIR /usr/src/app/

COPY gemini/.pylintrc gemini/.coveragerc ./gemini/
COPY gemini/gemini_scheduler/pyproject.toml gemini/gemini_scheduler/uv.lock ./gemini/gemini_scheduler/

RUN uv --project gemini/gemini_scheduler sync --locked
