ARG BUILDTAG=build
FROM herald:${BUILDTAG}
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/
LABEL org.opencontainers.image.authors="Hystax"

WORKDIR /usr/src/app/

COPY herald/pyproject.toml herald/uv.lock herald/
COPY tools/check_alembic_down_revisions tools/check_alembic_down_revisions
COPY optscale_client/herald_client optscale_client/herald_client

RUN uv --project herald sync --locked

COPY herald/herald_server/tests herald/herald_server/tests
COPY herald/modules/tests herald/modules/tests
